### PR TITLE
update the orage clock format

### PR DESCRIPTION
**Pull request by dolphinoracle**
update to orage clock format, not present in alpha 5

### CODE REVIEW

**Comment by pcallahan80** [comment]
What did I miss, D_O? (I'm glad I put this up on github...thanks for using it.)

**Comment by dolphinoracle** [comment]
The data0=%r should be data0=%H:%M

I thinky jerry decreed that data0=%H:%M should be the default, which is
24hr format.  My clock12or24 looks for %H and change it to %I for the 4
locales that use 12 hour clocks (USA, albania, eygpt, and greece).

No one who knows to look for the change will notice until 1 o'clock local
time!

**Comment by pcallahan80** [comment]
I just saw your change...(still figuring github.com out)...thanks for catching that.

**Comment by dolphinoracle** [comment]
by the way, awesome work on the uefi installer!  I think we are kicking its
tail!

**Comment by pcallahan80** [comment]
Yah, very very good work! Adrian was right to call the question on the process, though. I just sent him an email saying as much. We learned at a very fast pace, though. Many thanks to you. Still getting familiar with the efibootmgr tool and gdisk...we were definitely feeling around in the dark. At least I was.

**Comment by pcallahan80** [comment]
Hey, if we make changes here on the Panel, I should be able to send anti a Pull Request, right? I'll probably wait until the a5 gets out fully, though. What do you think?

**Comment by dolphinoracle** [comment]
I think you should go ahead and send it.  He may make another iso with
adrian's updated installer.  I noticed there is no announcement for a5, and
no 32 bit version.

**Comment by pcallahan80** [comment]
Okay, I'll see if I can figure it out...give him a longish note...

**Comment by pcallahan80** [comment]
Hey, D_O...how do make a Pull Request when anti hasn't forked from this repo. When I go to the compare button, I don't know what to put in the 'Base: master' and 'Compare: master'...

**Comment by dolphinoracle** [comment]
If he doens't have a repo, you can't.  You'll just have to email the file
too him.

it needs to go in both the demo account and /etc/skel

**Comment by pcallahan80** [comment]
Got it. Okay.

**Pull request merged**
